### ISSUE TITLE
Cannot open the video file

### ISSUE THREAD

**Issue by harshmunshi** [zhuolikevin/parkMonitor#1]
The code compiles fine but when I try to run it, I get the following output:

Cannot open the video file

and it stops.

I am using opencv 2.4.9, kindly help.

**Comment by zhuolikevin** [comment]
Did you use the video I provided or your own? And did you put it under `res/`?
I am not so sure what the exact reason it is, but there must be something wrong [here](https://github.com/zhuolikevin/Parking-Lot-Monitor/blob/master/src/monitorLauncher.cpp#L36)

I don't remember the opencv version I used. It was more than a year ago. Maybe the API changed? I have no idea.

Lol, sorry about that.

**Comment by harshmunshi** [comment]
or you can change the code
capture.open("source");

works fine :) :+1:
